# Generated by Django 4.2.10 on 2024-08-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('hallticket', models.FileField(upload_to='halltickets/')),
                ('result', models.FileField(upload_to='results/')),
            ],
        ),
    ]
