# Generated by Django 4.2.10 on 2024-08-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_student_hallticket_remove_student_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_name',
            field=models.CharField(default='RIVIN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='FUCK', max_length=100),
            preserve_default=False,
        ),
    ]
