# Generated by Django 4.2.10 on 2024-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_student_exam_address_student_mediam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_address',
            field=models.CharField(max_length=50),
        ),
    ]
