# Generated by Django 4.2.10 on 2024-08-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_student_stud_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='mediam',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='result',
            field=models.CharField(max_length=50),
        ),
    ]
