# Generated by Django 4.2.10 on 2024-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_student_exam_address_alter_student_mediam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sub1',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub2',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub3',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub4',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='total',
            field=models.IntegerField(max_length=50),
        ),
    ]
